name: Build (Tier 1 platforms)

# Triggered automatically on each push to main
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo


jobs:

  linux-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install libpcre3-dev libgtkmm-3.0-dev gettext

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: >
        cmake $GITHUB_WORKSPACE
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DAPP_BUILD_EXAMPLES=ON
        -DAPP_BUILD_TESTS=ON
        -DAPP_COMPILER_ENABLE_WARNINGS=ON

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Pack (cmake install and make binary package)
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE --target package

#    - name: Test
#      working-directory: ${{runner.workspace}}/build
#      shell: bash
#      run: ctest -C $BUILD_TYPE


  windows-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686 }
        ]

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            mingw-w64-${{ matrix.arch }}-gtkmm3
            mingw-w64-${{ matrix.arch }}-pkg-config
            mingw-w64-${{ matrix.arch }}-cmake
            mingw-w64-${{ matrix.arch }}-gcc
            make

      - name: Configure CMake
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}
        run: >
          cmake -B build -S "$GITHUB_WORKSPACE" -G "MSYS Makefiles" ..
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DAPP_BUILD_EXAMPLES=ON
          -DAPP_BUILD_TESTS=ON
          -DAPP_COMPILER_ENABLE_WARNINGS=ON

      - name: Build
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Install Package Requirements
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}/build
        run: >
          cmake -E make_directory ${{runner.workspace}}/build/smartmontools

          cd smartmontools

          wget https://nav.dl.sourceforge.net/project/smartmontools/smartmontools/7.2/smartmontools-7.2-1.win32-setup.exe

          7z e smartmontools-7.2-1.win32-setup.exe
          bin64/smartctl.exe bin64/smartctl-nc.exe
          bin/update-smart-drivedb.exe
          bin/drivedb.h

      - name: Package ZIP
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}/build
        run: cpack -G ZIP

      - name: Package NSIS (64-bit)
        if: ${{ matrix.msystem == 'MINGW64' }}
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}/build
        run: cpack -G NSIS64

      - name: Package NSIS (32-bit)
        if: ${{ matrix.msystem == 'MINGW32' }}
        shell: msys2 {0}
        working-directory: ${{runner.workspace}}/build
        run: cpack -G NSIS

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows Packages
          path: ${{runner.workspace}}/build/gsmartcontrol-*-win*.*

